# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pr:
  - master
  - master-hotfix

pool:
  vmImage: "ubuntu-latest"

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install -g @angular/cli
      npm install
    displayName: "npm install"

  - task: DeleteFiles@1
    inputs:
      SourceFolder: $(System.DefaultWorkingDirectory)/**/junit
      Contents: 'TESTS*.xml'
    displayName: 'Delete Previous Test Results Files'

  - script: |
      npm test -- --no-watch --code-coverage
    env:
      NODE_OPTIONS: --max_old_space_size=8048
    displayName: "Run Tests And Produce Coverage Reports"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: 'Install Python'

  - script: |
      python -m pip install --upgrade pip
      pip install diff_cover
    displayName: 'Install Python diff-cover Package'

  - script: |
      npm run code-diff-coverage
    displayName: "Run diff-cover"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: "**/TESTS*.xml"
      searchFolder: "$(System.DefaultWorkingDirectory)"
      failTaskOnFailedTests: true
      testRunTitle: Dashboard PR Unit Test Results
    displayName: "Publishing Test Results To Azure"

  - task: PublishCodeCoverageResults@1
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: Cobertura # or JaCoCo
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"
      failIfCoverageEmpty: false
    displayName: "Publishing Code Coverage Results To Azure"

  - script: |
      npm run build-azure
    displayName: "npm build"